[package]
name = "hyperscan"
version = "0.1.4"
authors = ["Flier Lu <flier.lu@gmail.com>"]
build = "build.rs"
description = "Hyperscan bindings for Rust with Multiple Pattern and Streaming Scan"
homepage = "http://flier.github.io/rust-hyperscan/"
repository = "https://github.com/flier/rust-hyperscan"
documentation = "http://flier.github.io/rust-hyperscan/doc/hyperscan/index.html"
license = "Apache-2.0"
readme = "README.md"
keywords = ["regex", "hyperscan", "streaming"]

[features]
gen = ["bindgen"]

[dependencies]
libc = "0.2"
log = "0.3"
regex-syntax = "0.4"

[build-dependencies]
log = "0.3"
env_logger = "0.4"
pkg-config = "0.3"

[build-dependencies.bindgen]
version = "0.22"
optional = true

[dev-dependencies]
env_logger = "0.4"
regex = "0.2"
getopts = "0.2"
pcap = "0.5"
pnet = "0.16"
byteorder = "1.0"

[lib]
name = "hyperscan"
doctest = false